# Site settings
title: Adrian Russell
copyright: "Copyright © Adrian Russell"
description: "Easily create shaders in Apple Metal with Tin Toy"
baseurl: ""
url: "https://tintoy.app"
github_username:   aderussell
linkedin_url: https://uk.linkedin.com/in/adrian-russell-4b15aa74

highlighter: none

# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
permalink: /blog/:year/:month/:day/:title

include: ['_tintoy']

sass:
    sass_dir: stylesheets
    style: compressed

gems:
    - jekyll-sitemap
    - jekyll-redirect-from